/*
Copyright 2013-present Barefoot Networks, Inc. 

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
/*
 * DO NOT EDIT:  This file is automatically generated.
 *
 */

#ifndef _ROCKER_p4_l2l3_H_
#define _ROCKER_p4_l2l3_H_

#define TABLES_DEFAULT_INIT_SIZE 65536 // entries


typedef struct rocker_p4_l2l3_port_vlan_mapping_entry_s {
  unsigned char key[9];
  int action_id;
  unsigned char action_data[4];

} rocker_p4_l2l3_port_vlan_mapping_entry_t;

typedef struct rocker_p4_l2l3_dmac_entry_s {
  unsigned char key[10];
  int action_id;
  unsigned char action_data[4];

} rocker_p4_l2l3_dmac_entry_t;

typedef struct rocker_p4_l2l3_smac_entry_s {
  unsigned char key[10];
  int action_id;
  unsigned char action_data[0];

} rocker_p4_l2l3_smac_entry_t;


#endif
